Repository WildCodeSchool-CDA-FT-2025-03/projet1_cody, pull requests merged in 2025-04, with the labels that each got.

#4 Feature@u.0.3 variable css/ryi
  client/src/App.css
  client/src/assets/.gitkeep
  client/src/assets/icons/.gitkeep
  client/src/assets/icons/add.svg
  client/src/assets/icons/book.svg
  client/src/assets/icons/edit.svg
  client/src/assets/icons/favorite.svg
  client/src/assets/icons/filtre-az.svg
  client/src/assets/icons/filtre-za.svg
  client/src/assets/icons/game.svg
  client/src/assets/icons/logo-hive-text.svg
  client/src/assets/icons/logo-hive.svg
  client/src/assets/icons/movie.svg
  client/src/assets/icons/music.svg
  client/src/assets/icons/search.svg
  client/src/assets/icons/star-empy.svg
  client/src/assets/icons/star-full.svg
  client/src/assets/icons/trash.svg
  client/src/assets/icons/trophy.svg
  client/src/assets/icons/user.svg
  client/src/index.css
Labels: Lead Review

#5 [FEAT] création de la navbar responsive
  client/src/components/NavRoot/NavRoot.module.css
  client/src/components/NavRoot/NavRoot.tsx
Labels: Change requested

#6 [FEAT] initialisation de l'entité movie
  server/db.sqlite
  server/src/config/sqlite.ts
  server/src/graphql/movie/.gitkeep
  server/src/graphql/movie/movie.entities.ts
  server/src/graphql/movie/movie.resolvers.ts
Labels: Reviewed, Lead Review, Correction faite

#7 Feature@u.0.8 book entity/adt
  server/src/config/sqlite.ts
  server/src/graphql/book/book.entities.ts
  server/src/graphql/book/book.resolvers.ts
  server/src/index.ts
Labels: Reviewed, Lead Review

#8 Feature@u.1.1 nouveaute home page
  client/src/App.css
  client/src/assets/images/avenger.jpg
  client/src/assets/images/music.jpeg
  client/src/components/ComponentsRoot/CardRoot.module.css
  client/src/components/ComponentsRoot/CardRoot.tsx
  client/src/components/ComponentsRoot/CarrouselRoot.module.css
  client/src/components/ComponentsRoot/CarrouselRoot.tsx
  client/src/index.css
  client/src/pages/HomePage/HomePage.module.css
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/StylePage.module.css
  client/src/types/Card.type.ts
Labels: Reviewed, Lead Review, Correction faite

#9 Feature@u.0.9 game many to many/adt
  server/src/config/sqlite.ts
  server/src/graphql/game/dlc_expansion.entities.ts
  server/src/graphql/game/game.entities.ts
  server/src/graphql/game/game.resolvers.ts
  server/src/graphql/game/game_award.entities.ts
  server/src/graphql/game/game_category.entities.ts
  server/src/graphql/game/platform.entities.ts
Labels: Reviewed, Lead Review, Correction faite

#11 Featured@u.2 movie page/ryi
  ConventionNommage.md
  client/src/assets/icons/arrow.svg
  client/src/assets/icons/search.svg
  client/src/components/ContentList/ContentList.module.css
  client/src/components/ContentList/ContentList.tsx
  client/src/components/ContentTitleAndBtnReturn/ContentTitleAndBtnReturn.module.css
  client/src/components/ContentTitleAndBtnReturn/ContentTitleAndBtnReturn.tsx
  client/src/components/NavRoot/NavRoot.tsx
  client/src/components/SearchAndFilter/SearchAndFilters.module.css
  client/src/components/SearchAndFilter/SearchAndFilters.tsx
  client/src/pages/ContentPage/ContentPage.module.css
  client/src/pages/ContentPage/ContentPage.tsx
  client/src/router/Router.tsx
  client/src/types/ContentType.ts
  client/src/types/GenreType.ts
Labels: Reviewed, Lead Review, Correction faite

#12 Feature@u.1.1 nouveaute home page
  client/src/assets/images/amelie.webp
  client/src/assets/images/avatar.webp
  client/src/assets/images/avenger.jpg
  client/src/assets/images/inception.jpg
  client/src/assets/images/intouchables.jpg
  client/src/assets/images/la-la-land.webp
  client/src/assets/images/le-parrain.jpg
  client/src/assets/images/le-roi-lion.webp
  client/src/assets/images/le-seigneur-des-anneaux.jpg
  client/src/assets/images/le-voyage-de-chihiro.jpg
  client/src/assets/images/music.jpeg
  client/src/assets/images/parasite.webp
  client/src/assets/images/the-dark-knight.jpg
  client/src/components/ComponentsRoot/CardRoot.module.css
  client/src/components/ComponentsRoot/CardRoot.tsx
  client/src/components/ComponentsRoot/CarrouselRoot.module.css
  client/src/components/ComponentsRoot/CarrouselRoot.tsx
  client/src/index.css
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/HomePage/MovieData.tsx
  client/src/types/card.type.ts
Labels: Reviewed, Lead Review

#14 Featured@u.0.10 migrate game/adt
  server/package.json
  server/src/config/migrate/games.json
  server/src/config/migrate/migrateGames.ts
  server/src/graphql/game/game_award.entities.ts
  server/src/graphql/game/game_category.entities.ts
  server/tsconfig.json
Labels: Reviewed

#15 Feature@u.0.5 music entity
  client/src/components/ContentList/fakeData.ts
  server/db.sqlite
  server/src/config/sqlite.ts
  server/src/graphql/music/album.entities.ts
  server/src/graphql/music/album_category.entities.ts
  server/src/graphql/music/artist.entities.ts
  server/src/graphql/music/lyricist.entities.ts
  server/src/graphql/music/music.resolvers.ts
  server/src/graphql/music/track.entities.ts
  server/src/index.ts
Labels: Reviewed, Lead Review, Correction faite

#17 [FEAT] creation des entitié many to many de movie
  server/.gitignore
  server/src/config/sqlite.ts
  server/src/graphql/movie/movie.entities.ts
  server/src/graphql/movie/movie_actors.entities.ts
  server/src/graphql/movie/movie_award.entities.ts
  server/src/graphql/movie/movie_category.entities.ts
Labels: Reviewed, Lead Review

#16 Feature@u8 game detail/adt
  client/.env.sample
  client/src/components/DetailRoot/DetailRoot.module.css
  client/src/components/DetailRoot/DetailRoot.tsx
  client/src/components/SpecificField/SpecificField.module.css
  client/src/components/SpecificField/SpecificField.tsx
  client/src/main.tsx
  client/src/pages/GameDetailPage/DetailPage.module.css
  client/src/pages/GameDetailPage/DetailPage.tsx
  client/src/router/Router.tsx
  client/src/services/apolloClient.ts
  server/src/graphql/game/game.resolvers.ts
Labels: Reviewed, Lead Review, Correction faite

#18 [FEAT] Migration des movies et types movies
  server/package.json
  server/src/config/migrate/migrateMovies.ts
  server/src/config/migrate/movies.json
  server/src/graphql/movie/movie.types.ts
Labels: Reviewed, Lead Review

#19 [ADD] ajout de l'url dans les entités
  server/src/config/migrate/migrateGames.ts
  server/src/config/migrate/migrateMovies.ts
  server/src/graphql/book/book.entities.ts
  server/src/graphql/game/game.entities.ts
  server/src/graphql/movie/movie.entities.ts
  server/src/graphql/movie/movie.types.ts
  server/src/graphql/music/album.entities.ts
Labels: Reviewed, Lead Review

#23 [FEAT] creation des entités et resolvers pour la newsletter
  server/src/config/sqlite.ts
  server/src/graphql/newsletter/newsletter.entities.ts
  server/src/graphql/newsletter/newsletter.resolvers.ts
  server/src/index.ts
Labels: Reviewed, Lead Review

#27 Feature@u.1.2 caroussels home/adt
  client/src/components/ComponentsRoot/CarrouselRoot.tsx
  client/src/pages/HomePage/HomePage.tsx
  server/src/graphql/game/game.resolvers.ts
  server/src/graphql/movie/movie.resolvers.ts
Labels: Reviewed

#26 Feature@u.0.10 maj data image/adt
  client/src/components/ComponentsRoot/CarrouselRoot.tsx
  client/src/pages/HomePage/HomePage.tsx
  server/src/config/migrate/games.json
  server/src/config/migrate/migrateGames.ts
  server/src/config/migrate/migrateMovies.ts
  server/src/config/migrate/movies.json
  server/src/graphql/game/game.resolvers.ts
  server/src/graphql/movie/movie.resolvers.ts
Labels: Reviewed

#28 [DOCS] modification du readme
  README.md
  client/public/screenshot-desktop.webp
  client/public/screenshot-mobile.webp
Labels: Reviewed, Lead Review

#24 Feature@u.2.2 get all ressource/adt
  client/src/components/ComponentsRoot/CardRoot.tsx
  client/src/components/ComponentsRoot/CarrouselRoot.tsx
  client/src/components/ContentList/ContentList.module.css
  client/src/components/ContentList/ContentList.tsx
  client/src/components/ContentList/fakeData.ts
  client/src/components/SearchAndFilter/SearchAndFilters.module.css
  client/src/components/SearchAndFilter/SearchAndFilters.tsx
  client/src/pages/ContentPage/ContentPage.module.css
  client/src/pages/ContentPage/ContentPage.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/schemas/General.schemas.ts
  client/src/types/Old-card.type.ts
  server/src/config/migrate/games.json
  server/src/config/migrate/migrateGames.ts
  server/src/config/migrate/migrateMovies.ts
  server/src/config/migrate/movies.json
  server/src/graphql/game/game.resolvers.ts
  server/src/graphql/general/general.entities.ts
  server/src/graphql/general/general.resolvers.ts
  server/src/graphql/movie/movie.resolvers.ts
  server/src/graphql/movie/movie.types.ts
  server/src/index.ts
Labels: Reviewed, Lead Review, Correction faite

#29 [FEAT] creation de la page mon profile et creation de la page ajout d…
  client/src/components/NavRoot/navItems.ts
  client/src/pages/AddMediaPage/AddMediaPage.module.css
  client/src/pages/AddMediaPage/AddMediaPage.tsx
  client/src/pages/ProfilePage/ProfilePage.module.css
  client/src/pages/ProfilePage/ProfilePage.tsx
  client/src/router/Router.tsx
  client/src/types/ContentType.ts
  client/src/types/ProfileCategory.ts
Labels: Reviewed, Lead Review

#31 [FEAT] Ajout Link sur card
  client/src/components/ComponentsRoot/CardRoot.module.css
  client/src/components/ComponentsRoot/CardRoot.tsx
  client/src/components/ComponentsRoot/CarrouselRoot.tsx
  client/src/pages/ContentPage/ContentPage.tsx
  client/src/pages/HomePage/HomePage.tsx
Labels: Change requested

#32 Feature@u8 design detailgame
  client/src/components/DetailRoot/DetailRoot.module.css
  client/src/components/DetailRoot/DetailRoot.tsx
  client/src/components/SpecificField/SpecificField.module.css
  client/src/components/SpecificField/SpecificField.tsx
  client/src/pages/GameDetailPage/DetailPage.module.css
  client/src/pages/GameDetailPage/DetailPage.tsx
Labels: Reviewed, Lead Review

#33 Correction général
  client/src/components/ComponentsRoot/CardRoot.tsx
  client/src/pages/HomePage/HomePage.module.css
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/ProfilePage/ProfilePage.tsx
Labels: Reviewed, Lead Review

#34 [FEAT] Ajout page détail film
  client/src/pages/MovieDetailPage/DetailPage.module.css
  client/src/pages/MovieDetailPage/DetailPage.tsx
  client/src/router/Router.tsx
  server/src/graphql/game/game.resolvers.ts
  server/src/graphql/general/general.resolvers.ts
  server/src/graphql/movie/movie.resolvers.ts
Labels: Reviewed, Lead Review, Correction faite

#35 Ajout d'une image par defaut
  client/src/assets/images/default.webp
  client/src/components/ComponentsRoot/CardRoot.tsx
Labels: Reviewed, Lead Review, Correction faite

#30 Feature@u.8.1.2 add form/ryi
  client/src/components/MediaForm/MediaForm.module.css
  client/src/components/MediaForm/MediaForm.tsx
  client/src/components/MediaForm/MediaTypeSelector.module.css
  client/src/components/MediaForm/MediaTypeSelector.tsx
  client/src/components/MediaForm/RenderField.tsx
  client/src/components/MediaForm/formFields.ts
  client/src/graphql/mutations/createGame.ts
  client/src/graphql/mutations/createMovie.ts
  client/src/pages/AddMediaPage/AddMediaPage.module.css
  client/src/pages/AddMediaPage/AddMediaPage.tsx
  client/src/services/apolloClient.ts
  client/src/types/FormType.ts
  server/src/graphql/game/game.resolvers.ts
  server/src/graphql/movie/movie.entities.ts
  server/src/graphql/movie/movie.resolvers.ts
  server/src/graphql/movie/movie_actors.entities.ts
  server/src/graphql/movie/movie_award.entities.ts
  server/src/graphql/movie/movie_category.entities.ts
Labels: Reviewed, Lead Review, Correction faite

#37 Retrait d'un filtre
  client/src/components/SearchAndFilter/SearchAndFilters.tsx
Labels: Reviewed, Lead Review

#38 [FIX] movie resolver
  server/src/graphql/movie/movie.resolvers.ts
Labels: Reviewed, Lead Review
